name: Build go binaries

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  # The “build” workflow 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: test_github_actions

    - name: Set up Go
      uses: test_github_actions
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
